/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kodein_db_leveldb_jni_LevelDBJNI_Iterator_AbstractBytesArray */

#ifndef _Included_org_kodein_db_leveldb_jni_LevelDBJNI_Iterator_AbstractBytesArray
#define _Included_org_kodein_db_leveldb_jni_LevelDBJNI_Iterator_AbstractBytesArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBJNI_Iterator_AbstractBytesArray
 * Method:    n_Release
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_org_kodein_db_leveldb_jni_LevelDBJNI_00024Iterator_00024AbstractBytesArray_n_1Release
  (JNIEnv *, jclass, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
