/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kodein_db_leveldb_jni_LevelDBJNI_NativeBytes */

#ifndef _Included_org_kodein_db_leveldb_jni_LevelDBJNI_NativeBytes
#define _Included_org_kodein_db_leveldb_jni_LevelDBJNI_NativeBytes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBJNI_NativeBytes
 * Method:    n_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_kodein_db_leveldb_jni_LevelDBJNI_00024NativeBytes_n_1Buffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBJNI_NativeBytes
 * Method:    n_Release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_kodein_db_leveldb_jni_LevelDBJNI_00024NativeBytes_n_1Release
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
