/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kodein_db_leveldb_jni_LevelDBJNI_Cursor_BytesArray */

#ifndef _Included_org_kodein_db_leveldb_jni_LevelDBJNI_Cursor_BytesArray
#define _Included_org_kodein_db_leveldb_jni_LevelDBJNI_Cursor_BytesArray
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
