package org.kodein.db.plugin.fts.stopwords

@OptIn(ExperimentalStdlibApi::class)
internal val dutchStopwords by lazy { buildSet {
    addAll(arrayOf("aan", "aangaande", "aangezien", "achte", "achter", "achterna", "af", "afgelopen", "al", "aldaar"))
    addAll(arrayOf("aldus", "alhoewel", "alias", "alle", "allebei", "alleen", "alles", "als", "alsnog", "altijd"))
    addAll(arrayOf("altoos", "ander", "andere", "anders", "anderszins", "beetje", "behalve", "behoudens", "beide", "beiden"))
    addAll(arrayOf("ben", "beneden", "bent", "bepaald", "betreffende", "bij", "bijna", "bijv", "binnen", "binnenin"))
    addAll(arrayOf("blijkbaar", "blijken", "boven", "bovenal", "bovendien", "bovengenoemd", "bovenstaand", "bovenvermeld", "buiten", "bv"))
    addAll(arrayOf("daar", "daardoor", "daarheen", "daarin", "daarna", "daarnet", "daarom", "daarop", "daaruit", "daarvanlangs"))
    addAll(arrayOf("dan", "dat", "de", "deden", "deed", "der", "derde", "derhalve", "dertig", "deze"))
    addAll(arrayOf("dhr", "die", "dikwijls", "dit", "doch", "doe", "doen", "doet", "door", "doorgaand"))
    addAll(arrayOf("drie", "duizend", "dus", "echter", "een", "eens", "eer", "eerdat", "eerder", "eerlang"))
    addAll(arrayOf("eerst", "eerste", "eigen", "eigenlijk", "elk", "elke", "en", "enig", "enige", "enigszins"))
    addAll(arrayOf("enkel", "er", "erdoor", "erg", "ergens", "etc", "etcetera", "even", "eveneens", "evenwel"))
    addAll(arrayOf("gauw", "ge", "gedurende", "geen", "gehad", "gekund", "geleden", "gelijk", "gemoeten", "gemogen"))
    addAll(arrayOf("genoeg", "geweest", "gewoon", "gewoonweg", "haar", "haarzelf", "had", "hadden", "hare", "heb"))
    addAll(arrayOf("hebben", "hebt", "hedden", "heeft", "heel", "hem", "hemzelf", "hen", "het", "hetzelfde"))
    addAll(arrayOf("hier", "hierbeneden", "hierboven", "hierin", "hierna", "hierom", "hij", "hijzelf", "hoe", "hoewel"))
    addAll(arrayOf("honderd", "hun", "hunne", "ieder", "iedere", "iedereen", "iemand", "iets", "ik", "ikzelf"))
    addAll(arrayOf("in", "inderdaad", "inmiddels", "intussen", "inzake", "is", "ja", "je", "jezelf", "jij"))
    addAll(arrayOf("jijzelf", "jou", "jouw", "jouwe", "juist", "jullie", "kan", "klaar", "kon", "konden"))
    addAll(arrayOf("krachtens", "kun", "kunnen", "kunt", "laatst", "later", "liever", "lijken", "lijkt", "maak"))
    addAll(arrayOf("maakt", "maakte", "maakten", "maar", "mag", "maken", "me", "meer", "meest", "meestal"))
    addAll(arrayOf("men", "met", "mevr", "mezelf", "mij", "mijn", "mijnent", "mijner", "mijzelf", "minder"))
    addAll(arrayOf("miss", "misschien", "missen", "mits", "mocht", "mochten", "moest", "moesten", "moet", "moeten"))
    addAll(arrayOf("mogen", "mr", "mrs", "mw", "na", "naar", "nadat", "nam", "namelijk", "nee"))
    addAll(arrayOf("neem", "negen", "nemen", "nergens", "net", "niemand", "niet", "niets", "niks", "noch"))
    addAll(arrayOf("nochtans", "nog", "nogal", "nooit", "nu", "nv", "of", "ofschoon", "om", "omdat"))
    addAll(arrayOf("omhoog", "omlaag", "omstreeks", "omtrent", "omver", "ondanks", "onder", "ondertussen", "ongeveer", "ons"))
    addAll(arrayOf("onszelf", "onze", "onzeker", "ooit", "ook", "op", "opnieuw", "opzij", "over", "overal"))
    addAll(arrayOf("overeind", "overige", "overigens", "paar", "pas", "per", "precies", "recent", "redelijk", "reeds"))
    addAll(arrayOf("rond", "rondom", "samen", "sedert", "sinds", "sindsdien", "slechts", "sommige", "spoedig", "steeds"))
    addAll(arrayOf("tamelijk", "te", "tegen", "tegenover", "tenzij", "terwijl", "thans", "tien", "tiende", "tijdens"))
    addAll(arrayOf("tja", "toch", "toe", "toen", "toenmaals", "toenmalig", "tot", "totdat", "tussen", "twee"))
    addAll(arrayOf("tweede", "u", "uit", "uitgezonderd", "uw", "vaak", "vaakwat", "van", "vanaf", "vandaan"))
    addAll(arrayOf("vanuit", "vanwege", "veel", "veeleer", "veertig", "verder", "verscheidene", "verschillende", "vervolgens", "via"))
    addAll(arrayOf("vier", "vierde", "vijf", "vijfde", "vijftig", "vol", "volgend", "volgens", "voor", "vooraf"))
    addAll(arrayOf("vooral", "vooralsnog", "voorbij", "voordat", "voordezen", "voordien", "voorheen", "voorop", "voorts", "vooruit"))
    addAll(arrayOf("vrij", "vroeg", "waar", "waarom", "waarschijnlijk", "wanneer", "want", "waren", "was", "wat"))
    addAll(arrayOf("we", "wederom", "weer", "weg", "wegens", "weinig", "wel", "weldra", "welk", "welke"))
    addAll(arrayOf("werd", "werden", "werder", "wezen", "whatever", "wie", "wiens", "wier", "wij", "wijzelf"))
    addAll(arrayOf("wil", "wilden", "willen", "word", "worden", "wordt", "zal", "ze", "zei", "zeker"))
    addAll(arrayOf("zelf", "zelfde", "zelfs", "zes", "zeven", "zich", "zichzelf", "zij", "zijn", "zijne"))
    addAll(arrayOf("zijzelf", "zo", "zoals", "zodat", "zodra", "zonder", "zou", "zouden", "zowat", "zulk"))
    addAll(arrayOf("zulke", "zullen", "zult"))
}}
