package org.kodein.db.plugin.fts.stopwords

@OptIn(ExperimentalStdlibApi::class)
internal val romanianStopwords by lazy { buildSet {
    addAll(arrayOf("a", "abia", "acea", "aceasta", "această", "aceea", "aceeasi", "acei", "aceia", "acel"))
    addAll(arrayOf("acela", "acelasi", "acele", "acelea", "acest", "acesta", "aceste", "acestea", "acestei", "acestia"))
    addAll(arrayOf("acestui", "aceşti", "aceştia", "acolo", "acord", "acum", "adica", "ai", "aia", "aibă"))
    addAll(arrayOf("aici", "aiurea", "al", "ala", "alaturi", "ale", "alea", "alt", "alta", "altceva"))
    addAll(arrayOf("altcineva", "alte", "altfel", "alti", "altii", "altul", "am", "anume", "apoi", "ar"))
    addAll(arrayOf("are", "as", "asa", "asemenea", "asta", "astazi", "astea", "astfel", "astăzi", "asupra"))
    addAll(arrayOf("atare", "atat", "atata", "atatea", "atatia", "ati", "atit", "atita", "atitea", "atitia"))
    addAll(arrayOf("atunci", "au", "avea", "avem", "aveţi", "avut", "azi", "aş", "aşadar", "aţi"))
    addAll(arrayOf("b", "ba", "bine", "bucur", "bună", "c", "ca", "cam", "cand", "capat"))
    addAll(arrayOf("care", "careia", "carora", "caruia", "cat", "catre", "caut", "ce", "cea", "ceea"))
    addAll(arrayOf("cei", "ceilalti", "cel", "cele", "celor", "ceva", "chiar", "ci", "cinci", "cind"))
    addAll(arrayOf("cine", "cineva", "cit", "cita", "cite", "citeva", "citi", "citiva", "conform", "contra"))
    addAll(arrayOf("cu", "cui", "cum", "cumva", "curând", "curînd", "când", "cât", "câte", "câtva"))
    addAll(arrayOf("câţi", "cînd", "cît", "cîte", "cîtva", "cîţi", "că", "căci", "cărei", "căror"))
    addAll(arrayOf("cărui", "către", "d", "da", "daca", "dacă", "dar", "dat", "datorită", "dată"))
    addAll(arrayOf("dau", "de", "deasupra", "deci", "decit", "degraba", "deja", "deoarece", "departe", "desi"))
    addAll(arrayOf("despre", "deşi", "din", "dinaintea", "dintr", "dintr-", "dintre", "doar", "doi", "doilea"))
    addAll(arrayOf("două", "drept", "dupa", "după", "dă", "e", "ea", "ei", "el", "ele"))
    addAll(arrayOf("era", "eram", "este", "eu", "exact", "eşti", "f", "face", "fara", "fata"))
    addAll(arrayOf("fel", "fi", "fie", "fiecare", "fii", "fim", "fiu", "fiţi", "foarte", "fost"))
    addAll(arrayOf("frumos", "fără", "g", "geaba", "graţie", "h", "halbă", "i", "ia", "iar"))
    addAll(arrayOf("ieri", "ii", "il", "imi", "in", "inainte", "inapoi", "inca", "incit", "insa"))
    addAll(arrayOf("intr", "intre", "isi", "iti", "j", "k", "l", "la", "le", "li"))
    addAll(arrayOf("lor", "lui", "lângă", "lîngă", "m", "ma", "mai", "mare", "mea", "mei"))
    addAll(arrayOf("mele", "mereu", "meu", "mi", "mie", "mine", "mod", "mult", "multa", "multe"))
    addAll(arrayOf("multi", "multă", "mulţi", "mulţumesc", "mâine", "mîine", "mă", "n", "ne", "nevoie"))
    addAll(arrayOf("ni", "nici", "niciodata", "nicăieri", "nimeni", "nimeri", "nimic", "niste", "nişte", "noastre"))
    addAll(arrayOf("noastră", "noi", "noroc", "nostri", "nostru", "nou", "noua", "nouă", "noştri", "nu"))
    addAll(arrayOf("numai", "o", "opt", "or", "ori", "oricare", "orice", "oricine", "oricum", "oricând"))
    addAll(arrayOf("oricât", "oricînd", "oricît", "oriunde", "p", "pai", "parca", "patra", "patru", "patrulea"))
    addAll(arrayOf("pe", "pentru", "peste", "pic", "pina", "plus", "poate", "pot", "prea", "prima"))
    addAll(arrayOf("primul", "prin", "printr-", "putini", "puţin", "puţina", "puţină", "până", "pînă", "r"))
    addAll(arrayOf("rog", "s", "sa", "sa-mi", "sa-ti", "sai", "sale", "sau", "se", "si"))
    addAll(arrayOf("sint", "sintem", "spate", "spre", "sub", "sunt", "suntem", "sunteţi", "sus", "sută"))
    addAll(arrayOf("sînt", "sîntem", "sînteţi", "să", "săi", "său", "t", "ta", "tale", "te"))
    addAll(arrayOf("ti", "timp", "tine", "toata", "toate", "toată", "tocmai", "tot", "toti", "totul"))
    addAll(arrayOf("totusi", "totuşi", "toţi", "trei", "treia", "treilea", "tu", "tuturor", "tăi", "tău"))
    addAll(arrayOf("u", "ul", "ului", "un", "una", "unde", "undeva", "unei", "uneia", "unele"))
    addAll(arrayOf("uneori", "unii", "unor", "unora", "unu", "unui", "unuia", "unul", "v", "va"))
    addAll(arrayOf("vi", "voastre", "voastră", "voi", "vom", "vor", "vostru", "vouă", "voştri", "vreme"))
    addAll(arrayOf("vreo", "vreun", "vă", "x", "z", "zece", "zero", "zi", "zice", "îi"))
    addAll(arrayOf("îl", "îmi", "împotriva", "în", "înainte", "înaintea", "încotro", "încât", "încît", "între"))
    addAll(arrayOf("întrucât", "întrucît", "îţi", "ăla", "ălea", "ăsta", "ăstea", "ăştia", "şapte", "şase"))
    addAll(arrayOf("şi", "ştiu", "ţi", "ţie"))
}}
