package org.kodein.db.plugin.fts.stopwords

@OptIn(ExperimentalStdlibApi::class)
internal val swedishStopwords by lazy { buildSet {
    addAll(arrayOf("aderton", "adertonde", "adjö", "aldrig", "alla", "allas", "allt", "alltid", "alltså", "andra"))
    addAll(arrayOf("andras", "annan", "annat", "artonde", "artonn", "att", "av", "bakom", "bara", "behöva"))
    addAll(arrayOf("behövas", "behövde", "behövt", "beslut", "beslutat", "beslutit", "bland", "blev", "bli", "blir"))
    addAll(arrayOf("blivit", "bort", "borta", "bra", "bäst", "bättre", "båda", "bådas", "dag", "dagar"))
    addAll(arrayOf("dagarna", "dagen", "de", "del", "delen", "dem", "den", "denna", "deras", "dess"))
    addAll(arrayOf("dessa", "det", "detta", "dig", "din", "dina", "dit", "ditt", "dock", "dom"))
    addAll(arrayOf("du", "där", "därför", "då", "e", "efter", "eftersom", "ej", "elfte", "eller"))
    addAll(arrayOf("elva", "emot", "en", "enkel", "enkelt", "enkla", "enligt", "ens", "er", "era"))
    addAll(arrayOf("ers", "ert", "ett", "ettusen", "fanns", "fem", "femte", "femtio", "femtionde", "femton"))
    addAll(arrayOf("femtonde", "fick", "fin", "finnas", "finns", "fjorton", "fjortonde", "fjärde", "fler", "flera"))
    addAll(arrayOf("flesta", "fram", "framför", "från", "fyra", "fyrtio", "fyrtionde", "få", "får", "fått"))
    addAll(arrayOf("följande", "för", "före", "förlåt", "förra", "första", "genast", "genom", "gick", "gjorde"))
    addAll(arrayOf("gjort", "god", "goda", "godare", "godast", "gott", "gälla", "gäller", "gällt", "gärna"))
    addAll(arrayOf("gå", "går", "gått", "gör", "göra", "ha", "hade", "haft", "han", "hans"))
    addAll(arrayOf("har", "heller", "hellre", "helst", "helt", "henne", "hennes", "hit", "hon", "honom"))
    addAll(arrayOf("hundra", "hundraen", "hundraett", "hur", "här", "hög", "höger", "högre", "högst", "i"))
    addAll(arrayOf("ibland", "icke", "idag", "igen", "igår", "imorgon", "in", "inför", "inga", "ingen"))
    addAll(arrayOf("ingenting", "inget", "innan", "inne", "inom", "inte", "inuti", "ja", "jag", "jo"))
    addAll(arrayOf("ju", "just", "jämfört", "kan", "kanske", "knappast", "kom", "komma", "kommer", "kommit"))
    addAll(arrayOf("kr", "kunde", "kunna", "kunnat", "kvar", "legat", "ligga", "ligger", "lika", "likställd"))
    addAll(arrayOf("likställda", "lilla", "lite", "liten", "litet", "länge", "längre", "längst", "lätt", "lättare"))
    addAll(arrayOf("lättast", "långsam", "långsammare", "långsammast", "långsamt", "långt", "låt", "man", "med", "mej"))
    addAll(arrayOf("mellan", "men", "mer", "mera", "mest", "mig", "min", "mina", "mindre", "minst"))
    addAll(arrayOf("mitt", "mittemot", "mot", "mycket", "många", "måste", "möjlig", "möjligen", "möjligt", "möjligtvis"))
    addAll(arrayOf("ned", "nederst", "nedersta", "nedre", "nej", "ner", "ni", "nio", "nionde", "nittio"))
    addAll(arrayOf("nittionde", "nitton", "nittonde", "nog", "noll", "nr", "nu", "nummer", "när", "nästa"))
    addAll(arrayOf("någon", "någonting", "något", "några", "nån", "nånting", "nåt", "nödvändig", "nödvändiga", "nödvändigt"))
    addAll(arrayOf("nödvändigtvis", "och", "också", "ofta", "oftast", "olika", "olikt", "om", "oss", "på"))
    addAll(arrayOf("rakt", "redan", "rätt", "sa", "sade", "sagt", "samma", "sedan", "senare", "senast"))
    addAll(arrayOf("sent", "sex", "sextio", "sextionde", "sexton", "sextonde", "sig", "sin", "sina", "sist"))
    addAll(arrayOf("sista", "siste", "sitt", "sitta", "sju", "sjunde", "sjuttio", "sjuttionde", "sjutton", "sjuttonde"))
    addAll(arrayOf("själv", "sjätte", "ska", "skall", "skulle", "slutligen", "små", "smått", "snart", "som"))
    addAll(arrayOf("stor", "stora", "stort", "större", "störst", "säga", "säger", "sämre", "sämst", "så"))
    addAll(arrayOf("sådan", "sådana", "sådant", "ta", "tack", "tar", "tidig", "tidigare", "tidigast", "tidigt"))
    addAll(arrayOf("till", "tills", "tillsammans", "tio", "tionde", "tjugo", "tjugoen", "tjugoett", "tjugonde", "tjugotre"))
    addAll(arrayOf("tjugotvå", "tjungo", "tolfte", "tolv", "tre", "tredje", "trettio", "trettionde", "tretton", "trettonde"))
    addAll(arrayOf("två", "tvåhundra", "under", "upp", "ur", "ursäkt", "ut", "utan", "utanför", "ute"))
    addAll(arrayOf("va", "vad", "var", "vara", "varför", "varifrån", "varit", "varje", "varken", "vars"))
    addAll(arrayOf("varsågod", "vart", "vem", "vems", "verkligen", "vi", "vid", "vidare", "viktig", "viktigare"))
    addAll(arrayOf("viktigast", "viktigt", "vilka", "vilkas", "vilken", "vilket", "vill", "väl", "vänster", "vänstra"))
    addAll(arrayOf("värre", "vår", "våra", "vårt", "än", "ännu", "är", "även", "åt", "åtminstone"))
    addAll(arrayOf("åtta", "åttio", "åttionde", "åttonde", "över", "övermorgon", "överst", "övre"))
}}
