= Kodein-DB

Multiplatform Kotlin embedded NoSQL database.


== Introduction

=== Description

Kodein DB is an embedded NoSQL database that works on JVM, Android, Kotlin/Native and iOS.
It is suited for client or mobile applications.

CAUTION: Under no circumstances should it be used for in a server!

.Kodein-DB allows you to:
- Easily store, retrieve and query data.
- Stop carrying about schema definitions.
- Easily set up a new project

.Kodein is a good choice because:
- It proposes a very simple and readable declarative DSL.
- It integrates nicely with Android and iOS.
- It proposes a very kotlin-esque idiomatic API.
- It can be used in plain Java.


=== Example

[source,kotlin]
.A simple example:
----
val db = DB.default.open("path/to/db")

db.put(User("John", "Doe"))
db.put(User("Jane", "Doe"))
db.put(User("Someone", "Else"))

val does = db.find<User>().byIndex("lastName", "Doe").models()
println(does.joinToString()) // Jane, John
----


== Install

=== JVM

==== With Maven

Add the repository:

[source,xml,subs="attributes"]
.pom.xml
----
&lt;repositories&gt;
    &lt;repository&gt;
      &lt;id&gt;jcenter&lt;/id&gt;
      &lt;url&gt;https://dl.bintray.com/kodein-framework/Kodein-DB&lt;/url&gt;
    &lt;/repository&gt;
&lt;/repositories&gt;
----

NOTE: Kodein-DB will eventually be sync'd with JCenter, when it exits beta.

Then add the dependency:

[source,xml,subs="attributes"]
.pom.xml
----
&lt;dependencies&gt;
    &lt;dependency&gt;
        &lt;groupId&gt;org.kodein.db&lt;/groupId&gt;
        &lt;artifactId&gt;kodein-db-jvm&lt;/artifactId&gt;
        &lt;version&gt;{version}&lt;/version&gt;
    &lt;/dependency&gt;
&lt;/dependencies&gt;
----

NOTE: If you are developing a library and not an application, use the artifact `kodein-db-api-jvm` instead, which only provides the Kodein-DB API, and not its implementation.


==== With Gradle

Add the repository:

[source,groovy,subs="attributes"]
.build.gradle
----
buildscript {
    repositories {
        maven { url "https://dl.bintray.com/kodein-framework/Kodein-DB" }
    }
}
----

NOTE: Kodein-DB will eventually be sync'd with JCenter, when it exits beta.

Then add the dependency:

[source,groovy,subs="attributes"]
.build.gradle
----
dependencies {
    implementation 'org.kodein.db:kodein-db-jvm:{version}'
}
----

NOTE: If you are developing a library and not an application, use the artifact `org.kodein.db:kodein-db-api-jvm:\{version}` instead, which only provides the Kodein-DB API, and not its implementation.


=== Multiplatform and/or Native (Gradle)

NOTE: Kodein-DB supports the following targets: +
      iosArm32, iosArm64, iosX64, linuxX64, macosX64, mingwX64

Kodein-DB uses the new gradle native dependency model, which is experimental in gradle.
You need to enable it in your `settings.gradle` file:

[source,groovy,subs="attributes"]
.settings.gradle
----
enableFeaturePreview("GRADLE_METADATA")
----

Then, in your `build.gradle` file, add the repository:

[source,groovy,subs="attributes"]
.build.gradle
----
buildscript {
    repositories {
        maven { url "https://dl.bintray.com/kodein-framework/Kodein-DB" }
    }
}
----

NOTE: Kodein-DB will eventually be sync'd with JCenter, when it exits beta.

Then add the dependency:

[source,groovy,subs="attributes"]
.build.gradle
----
kotlin {
    sourceSets {
        commonMain {
            dependencies {
                implementation "org.kodein.db:kodein-db:{version}"
            }
        }
    }
}
----

Thanks to Gradle Metadata, you don't need to add any additional dependency to your targets.

NOTE: If you are developing a library and not an application, use the artifact `org.kodein.db:kodein-db-api:\{version}` instead, which only provides the Kodein-DB API, and not its implementation.


== Immutability requirement

Kodein-DB works under the assumption that your models (ie. the objects that are going to be managed by the database) are immutable.
This can be seen as paradoxical for a database library: you need to be able to update your data!

Kodein-DB is a document based NoSQL library, it works much like a folder drawer.

- Inserting a document is like printing a new document and putting it inside the appropriate drawer at the correct position.
- Updating a document is like printing the updated document, and putting it inside the drawer, removing the old outdated document.

With this analogy, you can see that the document themselves are immutable: you do not scrible over a document, you print a new version to replace the old one.

Kodein-DB works the same way: each of your object model must be immutable, and you should create a new model to update one:

[source,kotlin]
.A simple example:
----
val john = db[db.newKey<User>("john-doe")] ?: error("No John!")
db.put(john.copy(phone = "0605040302"))
----

IMPORTANT: There is no way (yet?) in Kotlin to ensure immutability.
           While we cannot force you to use immutable models, we highly recommend that you do.
           Using mutable models will eventually lead to data races, and very hard to find bugs.

