= Kodein-DB
:toc: left
:toc-position: left
:toclevels: 5
:version: 0.1.0

Multiplatform Kotlin embedded NoSQL database.


== Introduction

=== Description

Kodein DB is an embedded NoSQL database that works on JVM, Android, Kotlin/Native and iOS.
It is suited for client or mobile applications.

CAUTION: Under no circumstances should it be used in a server!

.Kodein-DB allows you to:
- Easily store, retrieve and query kotlin objects.
- Stop carrying about schema definitions.
- Easily set up a new project.

.Kodein-DB is a good choice because it:
- proposes a very simple and readable DSL.
- integrates nicely with Android and iOS.
- offers very good performances.
- is just Kotlin!


=== Example

[source,kotlin]
.A simple example
----
val db = DB.open("path/to/db")

db.put(User("John", "Doe"))
db.put(User("Jane", "Doe"))
db.put(User("Someone", "Else"))

val does = db.find<User>().byIndex("lastName", "Doe").models()
println(does.joinToString()) // Jane, John
----


== Install

[IMPORTANT]
====
*Kodein-DB is in beta.*

Although, we do use Kodein-DB in production, this means we cannot ensure the library's correctness and stability.
Therefore, we ask that you first try Kodein-DB in non-critical applications, and report any mis-behaviour you may encounter.
====

=== JVM

Add the repository:

[source,groovy]
.build.gradle
----
buildscript {
    repositories {
        maven { url "https://dl.bintray.com/kodein-framework/Kodein-DB" }
    }
}
----

NOTE: Kodein-DB will eventually be sync'd with JCenter, when it exits beta.

Then add the dependency:

[source,groovy,subs=attributes+]
.build.gradle
----
dependencies {
    implementation 'org.kodein.db:kodein-db-jvm:{version}'
}
----

TIP: If you are developing a library and not an application, use the artifact `org.kodein.db:kodein-db-api-jvm:{version}` instead, which only provides the Kodein-DB API, and not its implementation.

Furthermore, you need to add the serializer you are going to use.
When targetting JVM only, you can use https://github.com/EsotericSoftware/kryo[Kryo]:

[source,groovy,subs=attributes+]
.build.gradle
----
dependencies {
    implementation 'org.kodein.db:kodein-db-serializer-kryo-jvm:{version}'
}
----

Finally, if you are targeting a desktop OS, you must add the OS specific leveldb native build dependency:

[source,groovy,subs=attributes+]
.build.gradle
----
dependencies {
    implementation 'org.kodein.db:kodein-leveldb-jni-linux:{version}' // 'linux' or 'macos'
}
----

TIP: If you are targeting multiple desktop OS, it is OK to add multiple `kodein-leveldb-jni-*` dependencies.


=== Multiplatform and/or Native (Gradle)

NOTE: Kodein-DB supports the following targets: +
      iosArm32, iosArm64, iosX64, linuxX64, macosX64, mingwX64

Kodein-DB uses the new gradle native dependency model, which is experimental in gradle.
You need to enable it in your `settings.gradle` file:

[source,groovy]
.settings.gradle
----
enableFeaturePreview("GRADLE_METADATA")
----

Then, in your `build.gradle` file, add the repository:

[source,groovy]
.build.gradle
----
buildscript {
    repositories {
        maven { url "https://dl.bintray.com/kodein-framework/Kodein-DB" }
    }
}
----

NOTE: Kodein-DB will eventually be sync'd with JCenter, when it exits beta.

Then add the dependency:

[source,groovy,subs=attributes+]
.build.gradle
----
kotlin {
    sourceSets {
        commonMain {
            dependencies {
                implementation "org.kodein.db:kodein-db:{version}"
            }
        }
    }
}
----

Thanks to Gradle Metadata, you don't need to add any additional dependency to your targets.

TIP: If you are developing a library and not an application, use the artifact `org.kodein.db:kodein-db-api:{version}` instead, which only provides the Kodein-DB API, and not its implementation.

Furthermore, you need to add the serializer you are going to use.
When targetting Multiplatform, you need to use https://github.com/Kotlin/kotlinx.serialization[KotlinX Serialization]:

[source,groovy,subs=attributes+]
.build.gradle
----
kotlin {
    sourceSets {
        commonMain {
            dependencies {
                implementation 'org.kodein.db:kodein-db-serializer-kotlinx:{version}'
            }
        }
    }
}
----


[[immutability]]
== Immutability requirement

Kodein-DB works under the assumption that your models (ie. the objects that are going to be managed by the database) are immutable.
This can be seen as paradoxical for a database library: you need to be able to update your data!

Kodein-DB is a document based NoSQL library, it works much like a folder drawer.

- Inserting a document is like printing a new document and putting it inside the appropriate drawer at the correct position.
- Updating a document is like printing the updated document, and putting it inside the drawer, removing the old outdated document.

With this analogy, you can see that the document themselves are immutable: you do not scrible over a document, you print a new version to replace the old one.

Kodein-DB works the same way: each of your object model must be immutable, and you should create a new model to update one:

[source,kotlin]
.A simple example
----
val john = db[johnKey] ?: error("No John!")
db.put(john.copy(phone = "0605040302"))
----

IMPORTANT: There is no way (yet?) in Kotlin to ensure immutability.
           While we cannot force you to use immutable models, we highly recommend that you do.
           Using mutable models will eventually lead to data races, and very hard to find bugs.


== Opening a database

=== Open statement

To open a new database, use `DB.factory`:

[source,kotlin]
.Opening a database
----
val db = DB.open("path/to/db")
----

By default, Kodein-DB will create the database if it does not exist.
If you want to modify this behaviour, you can use:

- `LevelDB.OpenPolicy.OPEN`: fails if the database does not already exist
- `LevelDB.OpenPolicy.CREATE`: fails if the database already exists

[source,kotlin]
.Opening an existing database
----
val db = DB.open("path/to/db", LevelDB.OpenPolicy.OPEN)
----


=== Defining the serializer

If you are targeting JVM only, then Kodein-DB will find the serializer by itself, so you don't need to define it. +
*However, when targeting Multiplatform, you need to define the KotlinX serializer and the serialized classes manually:*

[source,kotlin]
.Opening an existing database
----
val db = DB.open("path/to/db",
    KotlinXSerializer { //<1>
        +User.serializer() //<2>
        +Address.serializer() //<2>
    }
)
----
<1> Registers the KotlinX Serializer.
<2> Registers the class and associate serializer.


== Models

=== Metadata

IMPORTANT: *<<immutability>>*

==== ID and Indexes

A model *may* have *one or more* named indexes, to allow you to _search and/or order_ by a specific value.

A model *must* have *one* _unique_ ID, which can be of any type.
This ID defines the default ordering of the models inside the collections.
In essence, the ID works exactly like an index, except that it is unnamed.
You can use `UUID.randomUUID()` if your model does not have a unique value.

Indexes and IDs can be composite, which means that they can contain multiple values.
A composite index allows you to:

- Get models ordered by first value, then second, then third, then...
- Look for all models with the first value, then second, then third, then...


==== With annotations

When targeting *only the JVM*, you can simply use annotations:

[source,kotlin]
.A simple model
----
data class User(
    @Id val uid: String,
    val firstName: String,
    @Index("lastName") val lastName: String
)
----

CAUTION: When using `@Id` or `@Index`, Kodein-DB converts `String` values to byte array using the ASCII charset.
         Therefore, only ASCII characters are allowed.

Using this configuration, when getting all users by index `"lastName"`, they will be ordered first by `lastName`, then by `uid`.
If you want the results to be ordered by `lastName` then `firstName` (then `uid`), you can use a composite index:

[source,kotlin]
.Same model with composite index
----
data class User(
    @Id val uid: String,
    val firstName: String,
    val lastName: String
) {
    @Index("name") fun nameIndex() = listOf(lastName, firstName)
}
----


==== With the model

The model itself can define its metadata by implementing either the `Metadata` or `HasMetadata` interface:

[source,kotlin]
.Model *is* metadata
----
data class User(
    override val id: String, //<1>
    val firstName: String,
    val lastName: String
) : Metadata {
    override fun indexes() = indexSet("lastName" to listOf(lastName, firstName)) //<2>
}
----
<1> The `id` property override is mandatory
<2> The `indexes` function override is optional (no index by default)

[source,kotlin]
.Model *has* metadata
----
data class User(
    val id: String,
    val firstName: String,
    val lastName: String
) : HasMetadata {
    override fun getMetadata(db: ModelDB, vararg options: Options.Write) =
            Metadata(id, "lastName" to listOf(lastName, firstName))
}
----


==== With an extractor

If you don't own the models, or if you don't want to mark them for Kodein-DB, you can use register a `MetadataExtractor` when you open the database:

[source,kotlin]
.Registering a metadata extractor
----
val db = DB.open("path/to/db",
    MetadataExtractor {
        when (it) {
            is User -> Metadata(it.id, "lastName" to listOf(it.lastName, it.firstName))
            else -> error("Unknown model $it")
        }
    }
)
----


[[id-index]]
==== Using ID as an index

If we consider the `User` model we have just defined, we have defined the ID to be a UUID, meaning that the order in which they will be stored and retrieved is completely random. +
Because the ID must be unique, we cannot use the name to be the ID.
However, we can create a composite ID.
Consider this updated model:

[source,kotlin]
.Model with a composite ID
----
data class User(
    val uid: String,
    val firstName: String,
    val lastName: String
) : Metadata {
    override val id get() = listOf(lastName, firstName, uid)
}
----

Because `uid` is unique, the tuple `(lastName, firstName, uid)` is unique (if only because it contains `uid`).
Therefore, the `id` property is always unique, but the order in which the models will be stored are defined first by `lastName`, then by `firstName`, then only by `id`.

CAUTION: While using a composite ID can be very useful, it makes the <<key-from-id,creation of key from ID values>> more complex.


=== Key & References

If a model contains another model, it will be serialized into the same _document_.
If you need to reference another document, then you need to store a `Key`:

[source,kotlin]
.A model with a reference to another model
----
data class User(
    override val id: String,
    val name: Name, //<1>
    val address: Key<Address> //<2>
) : Metadata {
    override fun indexes() = indexSet("lastName" to listOf(name.last, name.first))
}
----
<1> Will be included as part of this model's document.
<2> References another model with its own document.


== Operations

=== Put, Delete, Get

Kodein-DB does not know the difference between Put and Update.
If you put a document that already exists in the database, it will be overwritten (you can, however, manually <<locking-check,check>> the existence and state of an overwritten model).

To put a document inside the database, simply use the `put` method:

[source,kotlin]
.Putting a model
----
val key = db.put(user) //<1>
----
<1> The `put` method returns the `Key` that refers to the model.

You can as easily delete a document:

[source,kotlin]
.Deleting a document
----
db.delete(key)
----

To get a model, simply use the `get` method:

[source,kotlin]
.Getting a model
----
val user = db[key]
----


=== Handling Keys

==== Definition

A `Key` is the unique identifier that identifies a document (and the associated model) inside the database.
It contains the following information:

- The type of the document (which is also the type of the model, unless you're using <<polymorphism,polymorphism>>).
- The Id of the document.

[TIP]
====
You can think of Kodein-DB as a file cabinet:

- The document type defines the drawer inside the cabinet.
- The document ID is the label that defines the document inside the drawer.
====

IMPORTANT: A key is specific to a Kodein-DB instance: a key refers to a model relative to a specific Kodein-DB.
           Do *not* share a Key: the same model with the same ID may give 2 different keys on two different databases.


==== Creating a Key

===== From a model

You can always ask Kodein-DB to provide you with the key of a specific model:

[source,kotlin]
.Creating a key
----
val key = db.key(user)
----

CAUTION: You can create a key from any model, whether it exists in database or not.
         Using `keyFrom` does *not* ensure you that the model exists in database, nor does it put it.


[[key-from-id]]
===== From ID values

You can easily create a key from its ID value(s):

[source,kotlin]
.Creating a key
----
val key = db.key<User>("01234567-89ab-cdef-0123-456789abcdef")
----

[IMPORTANT]
====
If you are using <<id-index,composite IDs>>, you need to provide all values of the ID. +
In the case of the earlier example, you would need to create the key as such:

[source,kotlin]
.Creating a key with a composite ID
----
val key = db.key<User>("Doe", "John", "01234567-89ab-cdef-0123-456789abcdef")
----
====


===== From a Base64 representation

Once you have a `Key` (either from `put` or `key`), you can serialize it to Base64:

[source,kotlin]
.serializing a key to Base64
----
val b64 = key.toBase64()
----

Then, you can re-create a key from a Base64 string:

[source,kotlin]
.deserializing a key from Base64
----
val key = db.keyFromB64(b64)
----

IMPORTANT: Even when serialized in Base64, a Key is only valid on the Kodein-DB that created it.


=== Iteration

[[getting-cursor]]
==== Getting a cursor

To iterate over a collection or a subset of a collection, you need to create cursor.

IMPORTANT: Cursors are `Closeable`! You need to either close them after use, or to call `use` on them.

You can iterate:

- Over all models of a collection, ordered by ID:
+
[source,kotlin]
----
val cursor = db.find<User>().all()
----
+
- Over all models of a collection whose composite ID begins with a specific value, ordered by id:
+
[source,kotlin]
----
val cursor = db.find<User>().byId("Doe")
----
+
- Over all models of a collection, ordered by an index:
+
[source,kotlin]
----
val cursor = db.find<User>().byIndex("lastName")
----
- Over all models of a collection with the specific index (composite or not) value, ordered by that index:
+
[source,kotlin]
----
val cursor = db.find<User>().byIndex("lastName", "Doe")
----
+
- Over all models of the database:
+
[source,kotlin]
----
val cursor = db.findAll()
----
+
CAUTION: When using `findAll()` on multiplatform projects, you *must* define a <<type-table,type table>> that defines all model classes!

NOTE: Cursors are working on a <<snapshot,snapshot>> of the database.
      This means that once an iterator is created, subsequent writes to the database won't be reflected in the result of the iteration.

==== Using a cursor

===== As is

By default, a cursor points to the first value of the matching query.

- You can get the key and model with `key()` and `model()`.
- You can move the cursor one item with `next()` and `previous()`, or directly to the start or end of the matching items with `seekToFirst` or `seekToLast`. +
- Each time the cursor moves, you need to check whether it is still valid with `isValid()`.

[source,kotlin]
.Iterating with a cursor
----
db.find<User>().byIndex("lastName", "Doe").use { cursor -> //<1>
    while (cursor.isValid()) {
        val model = cursor.model()
        println(model)
        cursor.next()
    }
}
----
<1> `use` ensures to close the cursor when iteration ends.


===== As a sequence

You can easily transform a `Cursor` to a `Sequence`.
Note that when you do, the cursor will be automatically closed when the sequence ends.

You can use either `models()` that creates a squence of models, or `entries`, that create a sequence of model and key pairs.

[source,kotlin]
.Iterating with a sequence
----
db.find<User>().byIndex("lastName", "Doe").models().forEach {
    println(it)
}
----

[CAUTION]
====
The sequence will only close when the last item has been collected!

The following code will *not* close the associated cursor and create a *resource leak*!

[source,kotlin]
.Creating a cursor leak
----
val first3 = db.find<User>().all()
    .models()
    .take(3) //<1>
    .toList()
----
<1> Because we take only the first 3 items, the last item of the cursor is never collected.

The correct way to do this is as such:

[source,kotlin]
.Getting the first 3 items without resource leak:
----
val first3 = db.find<User>().all().use { //<1>
    it.models()
        .take(3)
        .toList()
}
----
<1> `use` ensures to close the cursor when iteration ends.
====


[[polymorphism]]
== Polymorphism

=== The problem

By default, Kodein-DB inserts each model in the document collection that corresponds to its real type.

Considering the following insertions:

[source,kotlin]
.Multiple insertions
----
open class Person(@Id val name: String)
class Child(name: String, val parents: List<Key<Person>>): Person(name)

val janeKey = db.put(Person("Jane"))
val johnKey = db.put(Person("John"))

val parents = listOf(janeKey, johnKey)
db.put(Child("Jill", parents))
db.put(Person("Jack", parents))
----

Using the preceding code, there will be two different collections, one `Person`, one `Adult`, meaning if you were to look for all `Person` models, you would only get Jane & John.

Children are person too (even when they keep asking you when's the end of this documentation...) so, you probably want to put every `Child` model into the `Person` collection.
To do that, you need to enable polymorphism: the fact that a collection can hold multiple types of models.


=== JVM only annotation

The simpler way to define a polymorphic document is to use the `@Polymorphic` annotation.
However, as usual for annotations, *it only works for the JVM*.

[source,kotlin]
.Children are Persons
----
@Polymorphic(Person::class) //<1>
class Child(name: String, val parents: List<Key<Person>>): Person(name)
----
<1> This `@Polymorphic` annotation instructs Kodein-DB to put `Child` models into the `Person` collection.


[[type-table]]
=== Type Table

In Kodein-DB, the Type Table is responsible for defining which model type belongs to which collection.

NOTE: Using a Type Table is compatible with multiplatform!

You can define a `TypeTable` when opening the database:

[source,kotlin]
.Defining a Type Table
----
val db = DB.open("path/to/db",
    TypeTable {
        root<Person>() //<1>
            .sub<Child>() //<2>
    }
)
----
<1> Defines the root collection `Person`.
<2> Defines that all `Child` models will be put in the `Person` collection.


== Consistency

[[batch]]
=== Batch

A batch enables you to apply multiple write operations at once.
With a batch, you can ensure that neither a <<getting-cursor,cursor>> nor a <<snapshot,snapshot>> can reflect part of the operations of a batch.

IMPORTANT: Batches are `Closeable`! You need to either close them after use, or to call `use` on them.

[source,kotlin]
.Using a batch
----
db.newBatch().use {
    it.delete(oldAddress)
    val addressKey = it.put(newAddress)
    it.put(user.copy(address = addressKey))
    it.write() //<1>
}
----
<1> No modification will be applied to the database until `write()` is called.

[TIP]
====
If `write()` is not conditional before closing the batch, you can use `execBatch` that combines `use()` and `write()`:

[source,kotlin]
.Using and writing a batch
----
db.execBatch {
    delete(oldAddress)
    val addressKey = put(newAddress)
    put(user.copy(address = addressKey))
}
----
====


[[snapshot]]
=== Snapshot

A snapshot is a _read-only_ version of the database frozen at the time of creation.
Write operations that happen after the creation of a snapshot are not reflected to it.
Snapshot are most of the times used in conjunction with <<batch,batches>>.

IMPORTANT: Snapshots are `Closeable`! You need to either close them after use, or to call `use` on them.

[source,kotlin]
.Using a snapshot
----
val (user, address) = db.newSnapshot().use {
    val user = it[userKey]
    val address = it[user.address]
    user to address
}
----


== Being reactive

=== Listeners and subscriptions

Kodein-DB supports the reactive pattern.
You can use Kodein-DB as a data event hub, so that you can react to the addition or suppression of documents.

A listener is responsible for reacting to an operation. +
Once you have registered it, you can get a subscription `Closeable`, which will stop the listener from being called if you `close` it.


==== Using the DSL

You can easily register a listener using the ad-hoc DSL:

[source,kotlin]
.DSL listeners
----
db.on<User>().register { //<1>
}
db.onAll().register { //<2>
}
----
<1> Registers a listener on the `User` collection.
<2> Registers a global listener to the entire database.

A DSL listener can access its own subscription (this can be useful if you want the listener to cancel its own subscription after reacting to a certain event) in the context of the callbacks:

[source,kotlin]
.Accessing the subscription
----
db.on<User>().register {
    didPut { user ->
        if (whatever) this.subscription.close()
    }
}
----


==== Using the `DBListener` interface

You can have one of your classes implement the `DBListener` interface and then register it:

[source,kotlin]
.Class listeners
----
class UserListener : DBListener<User> {}
class GlobalListener : DBListener<Any> {}

val uSub = db.on<User>().register(UserListener()) //<1>
val aSub = db.onAll().register(GlobalListener()) //<2>
----
<1> Registers a listener on the `User` collection.
<2> Registers a global listener to the entire database.

A class listener receives its own subscription (this can be useful if you want the listener to cancel its own subscription after reacting to a certain event) just after registration:

[source,kotlin]
.Receiving the subscription
----
class UserListener : DBListener<User> {
    lateinit var subscription: Closeable
    override fun setSubscription(subscription: Closeable) {
        this.subscription = subscription
    }
}
----


=== Before an operation

==== simple check

You can use the event system to act _before_ an operation.

IMPORTANT: Any exception thrown in a `will*` callback cancels the operation (or batch of operation) and prevents subsequent callbacks to be called.

Reacting before an operation can be useful to ensure that the operation satisfies certain prerequisites, or to throw an exception to interrupt the operation if it isn't.

[source,kotlin]
.A DSL check
----
db.on<User>().register {
    willPut { user ->
        check(user.name.isNotBlank()) { "User firstName and lastName must not be blank" }
    }
    willDelete {
        val pictureCount = db.find<Picture>().byIndex("userKey", key).entries().count()
        check(pictureCount == 0) { "User has pictures, delete them first" }
    }
}
----

[source,kotlin]
.A class check
----
class UserListener : DBListener<User> {
    override fun willPut(model: User, typeName: ReadMemory, metadata: Metadata, options: Array<out Options.Write>) {
        check(model.name.isNotBlank()) { "User firstName and lastName must not be blank" }
    }
    override fun willDelete(key: Key<*>, getModel: () -> User?, typeName: ReadMemory, options: Array<out Options.Write>) {
        val pictureCount = db.find<Picture>().byIndex("userKey", key).entries().count()
        check(pictureCount == 0) { "User has pictures, delete them first" }
    }
}
----

==== Accessing the deleted model

You may have noticed in the preceding example that the `willDelete` callback do not access the deleted model.
That's because it is not given to the `willDelete` DSL callback. +
Because the deletion of a document uses its key, and not its model, you need to instruct the system to get the document before deleting it.

- Using the DSL, use the `willDeleteIt` method:
+
[source,kotlin]
.DSL delete check with model
----
db.on<User>().register {
    willDeleteIt { user ->
        val pictureCount = db.find<Picture>().byIndex("userId", user.id).entries().count()
        check(pictureCount == 0) { "User has pictures, delete them first" }
    }
}
----
+
- Using the class method, call the `getModel` function argument:
+
[source,kotlin]
.DSL delete check with model
----
class UserListener : DBListener<User> {
    override fun willDelete(key: Key<*>, getModel: () -> User?, typeName: ReadMemory, options: Array<out Options.Write>) {
        val user = getModel()
        val pictureCount = db.find<Picture>().byIndex("userId", user.id).entries().count()
        check(pictureCount == 0) { "User has pictures, delete them first" }
    }
}
----


=== After an operation

[[reaction]]
==== simple reaction

You can react after an operation, this can be useful:

- Locally if you want to keep or a local state (such as a UI) up to date:
- Globally if you want to keep a global state (such as the database itself) up to date.

NOTE: Any exception thrown from a `did*` callback will *not* prevent other listeners to be called.
      Kodein-DB ensures that all `did*` listeners are called when an operation has suceeded.

[source,kotlin]
.A DSL reaction
----
db.on<User>().register {
    didPut { user -> ui.add(user) }
    didDelete { ui.reload() }
}
----

[source,kotlin]
.A class reaction
----
class UserListener : DBListener<User> {
    override fun didPut(model: User, key: Key<*>, typeName: ReadMemory, metadata: Metadata, size: Int, options: Array<out Options.Write>) {
        ui.add(model)
    }
    override fun didDelete(key: Key<*>, model: User?, typeName: ReadMemory, options: Array<out Options.Write>) {
        ui.reload()
    }
}
----

Note that all arguments of the listener's methods are available in the DSL in the `this` context.

[TIP]
====
You can use `didDelete` to simulate cascading in a global listener:

[source,kotlin]
.DSL delete reaction with model
----
db.on<User>().register {
    didDelete {
        db.find<Picture>().byIndex("userKey", key).entries().forEach {
            db.delete(it.key)
        }
    }
}
----
====


==== Accessing the deleted model

You may have noticed in the preceding example that the `didDelete` callback do not access the deleted model.
That's because it is not given to the `didDelete` DSL callback, and will probably be null in the `didDelete` class method. +
Because the deletion of a document uses its key, and not its model, you need to instruct the system to get the document before deleting it.

- Using the DSL, simply use the `didDeleteIt` method:
+
[source,kotlin]
.DSL delete reaction with model
----
db.on<User>().register {
    didDeleteIt { user -> ui.remove(user) }
}
----
+
- Using the class method, call the `getModel` function argument in `willDelete`:
+
[source,kotlin]
.DSL delete reaction with model
----
class UserListener : DBListener<User> {
    override fun willDelete(key: Key<*>, getModel: () -> User?, typeName: ReadMemory, options: Array<out Options.Write>) {
        getModel()
    }
    override fun didDelete(key: Key<*>, model: User?, typeName: ReadMemory, options: Array<out Options.Write>) {
        ui.remove(model)
    }
}
----


[[context]]
=== Informing listeners

Sometimes, you need to pass some context to the listener(s).
Things like "Where is the operation coming from?" or "Why is this operation happening?".
In short, you may need to inform your listeners about _context_.

For example, you may want to know if you are creating a new `User`, or updating one.

Doing so is easy.
First, create a class that will hold the context and have it implement `Options.Write`:

[source,kotlin]
.A context class
----
enum class UserContext : Options.Write {
    NEW, UPDATE
}
----

Next, recover it from your listener:

[source,kotlin]
.Reading context in a listener
----
db.on<User>().register {
    didPut {
        val context = options.filterIsInstance<UserContext>().firstOrNull()
        when (context) {
            UserContext.NEW -> { /* insertion */ }
            UserContext.UPDATE -> { /* update */ }
            null -> { /* unknown */ }
        }
    }
}
----

Finally, don't forget to add the context option when you perform the operation:

[source,kotlin]
.Adding context to a put.
----
db.put(newUser, UserContext.NEW)
----


=== Local reactions

You may need to attach a callback to a specific operation or batch of operation.
For that, Kodein-DB provides the `Anticipate` and `React` options.


==== Regular

You can easilly add a check that will run before an operation is performed (this is especially usefull for a batch):

[source,kotlin]
.Adding context to a put.
----
db.put(newUser,
        Anticipate { println("Will put a user!") },
        React { println("Did put a user!") }
)

db.newBatch().use { batch ->
    batch.addOptions(
            Anticipate { println("Will write batch!") },
            React { println("Did write batch!") }
    )
}
----


== Advanced usage

=== Handling the cache

==== Definition

Kodein-DB provides an object-cache that reflects the data that is serialized inside the database. +
When querying for a data (either by `DB.get` or `DB.find`) if the needed data is already in the cache, then instead of de-serializing it, Kodein-DB immediately returns the cached value.

Kodein-DB updates the cache:
- at every `put` (both the database and the cache save the model)
- at every `get` or `find` (if the model is not in the cache, then the cache saves the model to prevent any future deserialization).

This enhances performances as deserialization is one of the most expensive operations.


==== Configuring at open

Kodein-DB allows you to pass multiple configuration values that modify cache behaviour when opening a database.

You may want to define the maximum size of the cache:

[source,kotlin]
.Opening a database:
----
val db = DB.open(
    "path/to/db",
    ModelCache.MaxSize(Runtime.getRuntime().totalMemory() / 8) //<1>
)
----
<1> Default on JVM & Android.

The cache also works on snapshots (remember: Kodein-DB automatically uses a snapshot when using a cursor or a sequence).
When you create a snapshot (or a cursor), it uses the same cache. +
However, if you mutate the database while holding a snapshot, than the cache must be copied in order for the snapshot to use a cache that only reflects the database when it was created.
This is a rare case (if you correctly close your cursors / snapshots) and only object references are copied, so the process itself is as optimised as can be.
However, you may need to handle the size of these snapshot-specific copies.

[source,kotlin]
.Opening a database:
----
val cacheSize = Runtime.getRuntime().totalMemory() / 8
val db = DB.open(
    "path/to/db",
    ModelCache.MaxSize(cacheSize),
    ModelCache.CopyMaxSize(cacheSize / 4) //<1>
)
----
<1> Default on JVM & Android.

Of course, if you don't want any caching, you can simply disable the cache:

[source,kotlin]
.Disabling the cache:
----
val db = DB.open(
    "path/to/db",
    ModelCache.Disable
)
----


==== Model skip & refresh

There are times when you may want to bypass the cache for a specific operation:

- When you *put* a model you won't need in the future:
+
[source,kotlin]
.Bypassing the cache:
----
db.put(model, ModelCache.Skip)
----
+
- When you *get* a model you won't query again in the future:
+
[source,kotlin]
.Bypassing the cache:
----
val m1 = db.get(model, ModelCache.Skip) //<1>
val m2 = db.get(model, ModelCache.Refresh) //<2>
----
<1> Skips the cache (and removes any cached value).
<2> Forces the cache to refresh from the serialized model in DB.


=== Using primitives

If you want a simple key-value collection, Kodein-DB provides optimized primitives for `Int`, `Long`, `Double` and `String`.
This can be useful for configuration-like values.

[source,kotlin]
.Using a primitive:
----
db.put(Primitive(id = "name", value = "John Doe"))
/*...*/
val name = db[db.key<StringPrimitive>("name")]?.value
----


[[locking-check]]
=== Locking checks and reactions

Both `Anticipate` and `React` can allow you to run the provided callback in a locked database (through the `needsLock` optional parameter).
Using this means that the database will be completely write-locked for the duration of the callback execution.

CAUTION: This can be very useful for things like transactions but can lead to dead locks and/or performance degradations.
Be extra-careful when using this feature !


[[values-and-buffers]]
=== Handling Values and Buffers

Kodein-DB uses https://github.com/Kodein-Framework/Kodein-Memory[Kodein-Memory] for its low-level bit-level memory manipulation.
Every memory that LevelDB (the low-level data store) handles is actually a `KBuffer`.

Kodein-DB uses the concept of `Value` to transform IDs and indexes to memory.
Every Kodein-DB API that takes an `Any` parameter for the ID or an index value can be slightly optimized by giving it the `Value` representation.
The optimization becomes more important for composite values.

[source,kotlin]
.Using Values:
----
db.find<Address>().byId(Value.ofAll(Value.ofAscii("France"), Value.ofInt(75000)))
----


=== Fine-graining (de)serialization

==== Writing your own optimised (de)serializers

If you want to handle a specific class serialization by yourself you can write your own serializer with the `org.kodein.db.model.orm.Serializer` interface:

[source,kotlin]
.Using specific serializer:
----
data class User(@Id val id: String, val name: String) {
    object S : Serializer<User> {
        override fun serialize(model: User, output: Writeable, vararg options: Options.Write) { //<1>
            output.putSizeAndString(model.id, Charset.ASCII)
            output.putSizeAndString(model.name, Charset.UTF8)
        }
        override fun deserialize(type: KClass<out User>, transientId: ReadMemory, input: ReadBuffer, vararg options: Options.Read): User { //<1>
            val id = input.readSizeAndString(Charset.UTF8)
            val name = input.readSizeAndString(Charset.UTF8)
            return User(id, name)
        }
    }
}
val db = DB.open("path/to/db",
        +User.S //<2>
)
----
<1> You can use <<context,context>> or specific options with the array of `Options.Write` options.
<2> Don't forget to *register the listener* when opening the database!


=== LevelDB Options

As Kodein-DB uses LevelDB underneath, you can pass various LevelDB specific configuration values:

[source,kotlin]
.Using LevelDB options:
----
val db = DB.open(
    "path/to/db",
    LevelDBOptions.PrintLogs(true)
)
----

Have a look at the `org.kodein.db.ldb.LevelDBOptions` sealed class for an overview of all available options.


=== Embedding your logic

==== Layered architecture

Kodein-DB uses a layered architecture: each layer transforms an operation into a "simpler" operation that can be then handled by a lower layer.

Here are the layers, from top to bottom:

- *API*: creates a nice API that can be used in a MPP application. This is the API you are using.
- *Cache*: Intercepts queries that would create a model already in cache and return that model instead.
- *Model*: Transforms a model into a document (a.k.a. serialized bytes and associated metadata) and vice versa.
- *Data*: Handles the document, its metadata and its indexes, transforming it to LevelDB entries.
- *LevelDB*: Stores and retrieves entries.

Kodein-DB allows you to add your own layers in this stack.

TIP: Most layer methods receive an array of options, which means that a middleware can recieve context or configuration the same way <<context,a listener receives it>>.


==== Model middleware

A model middleware sits between the *API* and the *Cache*.
In fact, the cache is itself a model middleware (added by default, unless disabled).

To implement a model middleware, use the `org.kodein.db.model.ModelDB` interface and the `org.kodein.db.Middleware.Model` container.

[source,kotlin]
----
typealias ModelMiddleware = ((ModelDB) -> ModelDB)
----

Here's a very simple model middleware that counts how many models you've put inside the database:

[source,kotlin]
.A put counter model middleware
----
class PutCountModelDB(val base: ModelDB, val count: AtomicInt) : ModelDB by base { //<1>
    override fun <M : Any> put(key: Key<M>, model: M, vararg options: Options.Write): Int {
        val ret = base.put(key, model, *options)
        count.incrementAndGet() //<2>
        return ret
    }

    override fun <M : Any> put(model: M, vararg options: Options.Write): KeyAndSize<M> {
        val ret = base.put(model, *options)
        count.incrementAndGet() //<2>
        return ret
    }

    override fun newBatch(): ModelBatch = PutCountModelBatch(base.newBatch(), count)
}

class PutCountModelBatch(val base: ModelBatch, val count: AtomicInt) : ModelBatch by base { //<1>
    private var willAdd = 0 //<3>

    override fun <M : Any> put(key: Key<M>, model: M, vararg options: Options.Write): Int {
        val ret = base.put(key, model, *options)
        willAdd += 1 //<2>
        return ret
    }

    override fun <M : Any> put(model: M, vararg options: Options.Write): KeyAndSize<M> {
        val ret = base.put(model, *options)
        willAdd += 1 //<2>
        return ret
    }

    override fun write(afterErrors: MaybeThrowable, vararg options: Options.Write) {
        base.write(afterErrors, *options)
        repeat(willAdd) { count.incrementAndGet() } //<3>
    }
}

fun putCountModelMiddleware(count: AtomicInt) =
        Middleware.Model { base -> PutCountModelDB(base, count) } //<4>
----
<1> Delegates every non-overloaded methods to the underneath layer
<2> Increment *after* the put operation, because it may fail
<3> Actually report the put operations only once the batch has been writen
<4> The middleware itself, that encapsulates the ModelDB layer inside the decorator.

NOTE: Counting count would be a lot easier with a simple <<reaction,listener>>.
      This is only a silly example!

Don't forget to actually add the middleware to the database when opening it!

[source,kotlin]
.Using LevelDB options:
----
val putCount = atomic(0)
val db = DB.open(
    "path/to/db",
    putCountModelMiddleware(putCount)
)
----

==== Data middleware

A data middleware sits between the *Data* and the *Model* layers.
It works exactly like a model middleware, except that you manipulate <<values-and-buffers,values and buffers>> instead of models and objects.

To implement a data middleware, use the `org.kodein.db.data.DataDB` interface and the `org.kodein.db.Middleware.Data` container.


==== LevelDB middleware

A LevelDB middleware sits between the *LevelDB* and the *Data* layers.
It works exactly like a data middleware, except that you manipulate raw data instead of documents, which means that a simple operation in Kodein-DB will probably lead to multiple operations at the LevelDB layer.

To implement a LevelDB middleware, use the `org.kodein.db.leveldb.LevelDB` interface and the `org.kodein.db.Middleware.Level` container.
