= Install

[[install-kmp]]
== Kotlin/Multiplatform

Kodein-DB uses the new gradle native dependency model featured in Gradle 5.3 and later.

In your `build.gradle.kts` file, add the repository:

[source,kotlin]
.build.gradle.kts
----
buildscript {
    repositories {
        mavenCentral()
    }
}
----

Then add the dependency:

[source,kotlin,subs=attributes+]
.build.gradle
----
kotlin {
    sourceSets {
        named("commonMain") {
            dependencies {
                implementation("org.kodein.db:kodein-db:{version}")
            }
        }
    }
}
----

Thanks to Gradle Metadata, you don't need to add any additional dependency to your targets.

[TIP]
====
If you are developing a library and not an application, use `kodein-db-api` instead, which only provides the Kodein-DB API, and not its implementation:

[source,kotlin,subs=attributes+]
----
implementation("org.kodein.db:kodein-db-api:{version}")
----
====

Furthermore, you need to add the serializer you are going to use.
When targeting Multiplatform, you can only use https://github.com/Kotlin/kotlinx.serialization[KotlinX Serialization]:

[source,kotlin,subs=attributes+]
.build.gradle
----
kotlin {
    sourceSets {
        named("commonMain") {
            dependencies {
                implementation("org.kodein.db:kodein-db-serializer-kotlinx:{version}")
            }
        }
    }
}
----


[[install-android]]
== Android only

Add the repository:

[source,kotlin]
.build.gradle.kts
----
buildscript {
    repositories {
        mavenCentral()
    }
}
----

Then add the dependency:

[source,kotlin,subs=attributes+]
.build.gradle.kts
----
dependencies {
    debugImplementation("org.kodein.db:kodein-db-android-debug:{version}")
    releaseImplementation("org.kodein.db:kodein-db-android:{version}")
}
----

[TIP]
====
If you are developing a library and not an application, use `kodein-db-api-jvm` instead, which only provides the Kodein-DB API, and not its implementation:

[source,kotlin,subs=attributes+]
----
implementation("org.kodein.db:kodein-db-api-jvm:{version}")
----
====

Furthermore, you need to add the serializer you are going to use.
When targetting Android only, you can use either https://github.com/Kotlin/kotlinx.serialization[KotlinX.Serialization]:

[source,kotlin,subs=attributes+]
.build.gradle.kts
----
dependencies {
    implementation("org.kodein.db:kodein-db-serializer-kotlinx:{version}")
}
----

...or https://github.com/EsotericSoftware/kryo[Kryo] (which is JVM & Android only):

[source,kotlin,subs=attributes+]
.build.gradle.kts
----
dependencies {
    implementation("org.kodein.db:kodein-db-serializer-kryo-jvm:{version}")
}
----


[[install-jvm]]
== Desktop JVM

Add the repository:

[source,kotlin]
.build.gradle.kts
----
buildscript {
    repositories {
        mavenCentral()
    }
}
----

Then add the dependency:

[source,kotlin,subs=attributes+]
.build.gradle.kts
----
implementation("org.kodein.db:kodein-db-jvm:{version}")
----

[TIP]
====
If you are developing a library and not an application, use `kodein-db-api-jvm` instead, which only provides the Kodein-DB API, and not its implementation:

[source,kotlin,subs=attributes+]
----
dependencies {
    implementation("org.kodein.db:kodein-db-api-jvm:{version}")
}
----
====

Furthermore, you need to add the serializer you are going to use.
When targetting JVM only, you can use either https://github.com/Kotlin/kotlinx.serialization[KotlinX.Serialization]:

[source,kotlin,subs=attributes+]
.build.gradle.kts
----
dependencies {
    implementation("org.kodein.db:kodein-db-serializer-kotlinx:{version}")
}
----

...or https://github.com/EsotericSoftware/kryo[Kryo] (which is JVM & Android only):

[source,kotlin,subs=attributes+]
.build.gradle.kts
----
dependencies {
    implementation("org.kodein.db:kodein-db-serializer-kryo-jvm:{version}")
}
----

Finally, you must add the OS specific leveldb native build dependency:

[source,kotlin,subs=attributes+]
.build.gradle.kts
----
dependencies {
    implementation("org.kodein.db:kodein-leveldb-jni-jvm-linux:{version}")
    //                                                  -linux, -macos or -windows
}
----

TIP: If you are targeting multiple desktop OS, you can use the `kodein-leveldb-jni-jvm` dependency, which imports all three (Linux, MacOS & Windows) artifacts.
