= Being reactive

Kodein-DB supports the reactive pattern.
You can use Kodein-DB as a data event hub, so that you can react to the addition or suppression of documents.

Kodein-DB supports various APIs to anticipate or react to Database writes:

- A `Listener` can anticipate or react to any write event.
- A KotlinX Coroutines `Flow` can be used to react to any write event.
- A KotlinX Coroutines `StateFlow` can be used to always get the latest version of a model.


== Listeners

A listener is responsible for anticipating and/or reacting to an operation. +


=== Subscription


==== Using the DSL

You can easily register a listener using the ad-hoc DSL:

[source,kotlin]
.DSL listeners
----
val cSub = db.on<Contact>().register { //<1>
}
val aSub = db.onAll().register { //<2>
}
----
<1> Registers a listener on the `Contact` collection.
<2> Registers a global listener to the entire database.

A DSL listener can access its own subscription (this can be useful if you want the listener to cancel its own subscription after reacting to a certain event) in the context of the callbacks:

[source,kotlin]
.Accessing the subscription
----
val cSub = db.on<Contact>().register {
    didPut { contact ->
        if (whatever) this.subscription.close()
    }
}
----


==== Using the `DBListener` interface

You can have one of your classes implement the `DBListener` interface and then register it:

[source,kotlin]
.Class listeners
----
class ContactListener : DBListener<Contact> {}
class GlobalListener : DBListener<Any> {}

val cSub = db.on<Contact>().register(ContactListener()) //<1>
val aSub = db.onAll().register(GlobalListener()) //<2>
----
<1> Registers a listener on the `Contact` collection.
<2> Registers a global listener to the entire database.

A class listener receives its own subscription (this can be useful if you want the listener to cancel its own subscription after reacting to a certain event) just after registration:

[source,kotlin]
.Receiving the subscription
----
class ContactListener : DBListener<Contact> {
    lateinit var subscription: Closeable
    override fun setSubscription(subscription: Closeable) {
        this.subscription = subscription
    }
}
----


==== Unsubscribe

Once you have registered a listener, you can use its subscription to unregister it:

[source,kotlin]
.Unsubscribing a listener
----
sub.close()
----


=== Anticipate & check before an operation

You can use the event system to act _before_ an operation.

IMPORTANT: Any exception thrown in a `will*` callback cancels the operation (or batch of operation) and prevents subsequent callbacks to be called.

Reacting before an operation can be useful to ensure that the operation satisfies certain prerequisites, or to throw an exception to interrupt the operation if it isn't.

[source,kotlin]
.A DSL check
----
db.on<Contact>().register {
    willPut { contact ->
        check(contact.name.isNotBlank()) { "Contact firstName and lastName must not be blank" }
    }
    willDelete {
        val pictureCount = db.find<Picture>().byIndex("contactKey", key).entries().count()
        check(pictureCount == 0) { "Contact has pictures, delete them first" }
    }
}
----

Note that if you need the actual model in a `willDelete` callback, you need to use `willDeleteIt`:

[source,kotlin]
.A DSL delete check with model
----
db.on<Contact>().register {
    willDeleteIt { contact ->
        val pictureCount = db.find<Picture>().byIndex("contactId", contact.id).entries().count()
        check(pictureCount == 0) { "Contact has pictures, delete them first" }
    }
}
----

The same example with a Listener object:

[source,kotlin]
.A Listener object check
----
class ContactListener : DBListener<Contact> {
    override fun willPut(operation: Operation.Put<Model>) {
        check(operation.model.name.isNotBlank()) { "Contact firstName and lastName must not be blank" }
    }
    override fun willDelete(operation: Operation.Delete<Model>) {
        val pictureCount = db.find<Picture>().byIndex("contactKey", operation.key).entries().count()
        check(pictureCount == 0) { "Contact has pictures, delete them first" }
    }
}
----


[[reaction]]
=== React after an operation

You can react after an operation, this can be useful:

- Locally if you want to keep a local state (such as a UI) up to date:
- Globally if you want to keep a global state (such as the database itself) up to date.

NOTE: Any exception thrown from a `did*` callback will *not* prevent other listeners to be called.
Kodein-DB ensures that all `did*` callbacks are called when an operation has suceeded.

[source,kotlin]
.A DSL reaction
----
db.on<Contact>().register {
    didPut { contact -> ui.add(contact) }
    didDelete { ui.reload() }
}
----

Note that if you need the actual model in a `didDelete` callback, you need to use `didDeleteIt`:

[source,kotlin]
.A DSL reaction check with model
----
db.on<Contact>().register {
    didDeleteIt { contact ->
        showDeletedConfirmation(contact.name)
    }
}
----

The same example with a Listener object:

[source,kotlin]
.A class reaction
----
class ContactListener : DBListener<Contact> {
    override fun didPut(operation: Operation.Put<Contact>) {
        ui.add(operation.model)
    }
    override fun didDelete(operation: Operation.Delete<Contact>) {
        ui.reload()
    }
}
----

[IMPORTANT]
====
The `operation.model()` function in `didDelete` only returns a nullable model and will return `null` by default.
If you need to access the model in the `didDelete` callback, you need to instruct the system to get it before it is deleted:

[source,kotlin]
.DSL delete reaction with model
----
class ContactListener : DBListener<Contact> {
    override fun willDelete(operation: Operation.Delete<Contact>) {
        operation.model() // Instructs to get the model before it is deleted
    }
    override fun didDelete(operation: Operation.Delete<Contact>) {
        ui.remove(operation.model())
    }
}
----
====


== KotlinX Coroutines: Flows & StateFlows

Kodein-DB offers APIs using KotlinX Coroutines https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/[Flow] & https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/[StateFlow].

NOTE: Flows allow you to *react* _after_ a change. +
      To anticipate and/or check _before_ a change, you must use listeners.


=== Flows

You can use KotlinX Coroutines https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/[`Flow`]s to watch a collection for changes:

[source,kotlin]
.DB Flows
----
val puts: Flow<Operation.Put<Contact>> = db.on<Contact>().putFlow()
val deletes: Flow<Operation.Delete<Contact>> = db.on<Contact>().deleteFlow()
val operations: Flow<Operation<Contact>> = db.on<Contact>().operationFlow()
----

With flows, you can simply react to a change in the entire collection, or just a subset:

[source,kotlin]
.Reacting to a subset
----
launch {
    db.on<Contact>().putFlow()
        .filter { it.model.lastName == "Doe" }
        .collect {
            println("Added a new member to the Doe family: ${it.model}")
        }
}
----

You can also react to any change in the database, whatever the collection:

[source,kotlin]
.Reacting to everything!
----
launch {
    db.onAll().operationFlow()
        .collect {
            when (it) {
                is Operation.Put -> println("Added ${it.model}")
                is Operation.Delete -> println("Removed ${it.model()}")
            }

        }
}
----


=== StateFlows

You can use KotlinX Coroutines https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/[`StateFlow`]s to always stay up to date to a model:

[source,kotlin]
.Getting a StateFlow
----
launch {
    val stateFlow = db.stateFlowOfId<Contact>(this, "f9d01ffa-7cc4-4291-aeea-4bd31014fd63")
}
----

You can also obtain a `StateFlow` from a key with `stateFlowOf` and from a model with `stateFlowFrom`.

TIP: In Android, `StateFlow` are the new https://medium.com/androiddevelopers/migrating-from-livedata-to-kotlins-flow-379292f419fb[recommended solution], and link:++https://developer.android.com/reference/kotlin/androidx/lifecycle/package-summary#(kotlinx.coroutines.flow.Flow).asLiveData(kotlin.coroutines.CoroutineContext,%20kotlin.Long)++[compatible] with LiveData.


[[context]]
== Informing listeners

Sometimes, you need to pass some context to the listener(s).
Things like "Where is the operation coming from?" or "Why is this operation happening?".
In short, you may need to inform your listeners about _context_.

For example, you may want to know if you are creating a new `Contact`, or updating one.

Doing so is easy.
First, create a class that will hold the context and have it implement `Options.Listeners`:

[source,kotlin]
.A context class
----
enum class ContactContext : Options.Listeners {
    NEW, UPDATE
}
----

Next, recover it...

- ...from your listener:
+
[source,kotlin]
.Reading context in a listener
----
db.on<Contact>().register {
    didPut {
        val context = options.filterIsInstance<ContactContext>().firstOrNull()
        when (context) {
            ContactContext.NEW -> { /* insertion */ }
            ContactContext.UPDATE -> { /* update */ }
            null -> { /* unknown */ }
        }
    }
}
----
- ...from your flow:
+
[source,kotlin]
.Reading context in a flow
----
db.on<Contact>().putFlow().collect {
        val context = it.options.filterIsInstance<ContactContext>().firstOrNull()
        when (context) {
            ContactContext.NEW -> { /* insertion */ }
            ContactContext.UPDATE -> { /* update */ }
            null -> { /* Wasn't provided */ }
        }
    }
}
----


Finally, don't forget to add the context option when you perform the operation:

[source,kotlin]
.Adding context to a put.
----
db.put(newContact, ContactContext.NEW)
----


== Local reactions

You may need to attach a callback to a specific operation or batch of operation.
For that, Kodein-DB provides the `Anticipate` and `React` options.

You can easily add a check that will run before an operation is performed (this is especially usefull for a batch):

[source,kotlin]
.Adding context to a put.
----
db.put(newContact,
        Anticipate { println("Will put a contact!") },
        React { println("Did put a contact!") }
)

db.newBatch().use { batch ->
    batch.write(
            Anticipate { println("Will write batch!") },
            React { println("Did write batch!") }
    )
}
----
