= Testing your DB code

Kodein-DB provides an in-memory backend which does not need any filesystem and stores all documents in a big `HashMap`.

IMPORTANT: *Never use this in production!* +
           This backend is absolutely not optimised neither for performance nor for memory packing.
           It is *only meant for testing*!

== Install

Add the `kodein-db-inmemory` module dependency:

[source,kotlin,subs=attributes+]
.build.gradle.kts
----
dependencies {
    implementation("org.kodein.db:kodein-db-inmemory:{version}")
}
----


== Use

=== Opening

To create an in-memory database, use the `DB.inMemory` factory:

[source,kotlin]
.Opening an in-memory test database
----
val db = DB.inMemory.open("my-db-name", options)
----

`DB.inMemory` implements the `DBFactory<DB>` interface, which means that you can easily create a factory function that abstracts your database configuration:

[source,kotlin]
.Opening an in-memory test database
----
fun createDatabase(val factory: DBFactory<DB>, dir: String): DB =
    factory.open(
        "$dir/app-db",
        KotlinxSerializer {
            +User.serializer()
            +Address.serializer()
        },
        TypeTable {
            root<Address>()
                .sub<BillingAddress>()
                .sub<DeliveringAddress>()
        }
    )

val realDb = createDatabase(DB.default, getApplicationDirectory())
val testDb = createDatabase(DB.inMemory, "fake")
----


=== Persistence

In memory Kodein-DB does not persist across processes (Duh!) but it does persist when closing an in-memory db and re-opening one with the same name.
This is why, in your tests, you need to destroy any existing in-memory database with the same name:

[source,kotlin]
.Test hooks
----
@BeforeTest
fun setUp() {
    DB.inMemory.destroy("fake")
    db = createDatabase(DB.inMemory, "fake")
}

@AfterTest
fun tearDown() {
    db.close()
}
----

NOTE: Calling `destroy` on a nonexistent database is safe and has no effect.
