/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kodein_db_leveldb_jni_LevelDBNative_Iterator_NativeBytesArray */

#ifndef _Included_org_kodein_db_leveldb_jni_LevelDBNative_Iterator_NativeBytesArray
#define _Included_org_kodein_db_leveldb_jni_LevelDBNative_Iterator_NativeBytesArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBNative_Iterator_NativeBytesArray
 * Method:    n_Release
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_org_kodein_db_leveldb_jni_LevelDBNative_00024Iterator_00024NativeBytesArray_n_1Release
  (JNIEnv *, jclass, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
