/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kodein_db_leveldb_jni_LevelDBNative_Snapshot */

#ifndef _Included_org_kodein_db_leveldb_jni_LevelDBNative_Snapshot
#define _Included_org_kodein_db_leveldb_jni_LevelDBNative_Snapshot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBNative_Snapshot
 * Method:    n_Release
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_kodein_db_leveldb_jni_LevelDBNative_00024Snapshot_n_1Release
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
