/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kodein_db_leveldb_jni_LevelDBNative_Iterator */

#ifndef _Included_org_kodein_db_leveldb_jni_LevelDBNative_Iterator
#define _Included_org_kodein_db_leveldb_jni_LevelDBNative_Iterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBNative_Iterator
 * Method:    n_Valid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kodein_db_leveldb_jni_LevelDBNative_00024Iterator_n_1Valid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBNative_Iterator
 * Method:    n_SeekToFirst
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_kodein_db_leveldb_jni_LevelDBNative_00024Iterator_n_1SeekToFirst
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBNative_Iterator
 * Method:    n_SeekToLast
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_kodein_db_leveldb_jni_LevelDBNative_00024Iterator_n_1SeekToLast
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBNative_Iterator
 * Method:    n_Seek_B
 * Signature: (JLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_kodein_db_leveldb_jni_LevelDBNative_00024Iterator_n_1Seek_1B
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBNative_Iterator
 * Method:    n_Seek_A
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_org_kodein_db_leveldb_jni_LevelDBNative_00024Iterator_n_1Seek_1A
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBNative_Iterator
 * Method:    n_Next
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_kodein_db_leveldb_jni_LevelDBNative_00024Iterator_n_1Next
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBNative_Iterator
 * Method:    n_Prev
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_kodein_db_leveldb_jni_LevelDBNative_00024Iterator_n_1Prev
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBNative_Iterator
 * Method:    n_key
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_kodein_db_leveldb_jni_LevelDBNative_00024Iterator_n_1key
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBNative_Iterator
 * Method:    n_value
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_kodein_db_leveldb_jni_LevelDBNative_00024Iterator_n_1value
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBNative_Iterator
 * Method:    n_NextArray
 * Signature: (J[J[Ljava/nio/ByteBuffer;[I[I[I[II)V
 */
JNIEXPORT void JNICALL Java_org_kodein_db_leveldb_jni_LevelDBNative_00024Iterator_n_1NextArray
  (JNIEnv *, jclass, jlong, jlongArray, jobjectArray, jintArray, jintArray, jintArray, jintArray, jint);

/*
 * Class:     org_kodein_db_leveldb_jni_LevelDBNative_Iterator
 * Method:    n_Release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_kodein_db_leveldb_jni_LevelDBNative_00024Iterator_n_1Release
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
