/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kodein_db_leveldb_jni_LevelDBNative_Snapshot_Companion */

#ifndef _Included_org_kodein_db_leveldb_jni_LevelDBNative_Snapshot_Companion
#define _Included_org_kodein_db_leveldb_jni_LevelDBNative_Snapshot_Companion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
